FROM python:3.10

WORKDIR /scrapper

COPY ./bot ./bot
COPY ./config ./config

COPY requirements.txt .

RUN mkdir db
RUN mkdir log

RUN python3 -m pip install -r requirements.txt

ENTRYPOINT ["python3", "bot/scrap_bot.py"]